# apiVersion: apps/v1 # which api to use for deployment

# kind: Deployment # what kind of service/object do you want to create?

# # what would you like to call it - name the service/object


# metadata:
#   name: app-deployment
# spec:
#   selector: 
#     matchLabels:
#       app: node
#   replicas: 3

#   template:
#     metadata:
#       labels:
#         app: node
    
#     spec: 
#       containers:
#       - name: node
#         image: billy5549/tech221-app:v1
#         ports:
#         - containerPort: 3000
#         env:
#           - name: DB_HOST
#             value: mongodb://mongo:27017/posts
#         imagePullPolicy: Always

#         resources:
#           limits:
#             memory: 512Mi
#             cpu: "1"
#           requests:
#             memory: 256Mi
#             cpu: "0.2"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1
  template: 
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: billy5549/tech221-app:v1
          
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mongodb://10.104.186.173 :27017/posts
          
          imagePullPolicy: Always

          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"