---
# select the type of API version and type of service
apiVersion: v1
kind: Service

# metadata for name
metadata:
  name: mongo-svc
  namespace: default # sre

# specification to include poirts selector to connect to the
spec: 
  ports:
  - nodePort: 30003 # range is 30000 - 32768
    port: 27017

    targetPort: 27017

# define the selector and label to connect to nginx
  selector:
    app: mongo

# creating a nodeport type of deployment
  type: NodePort # also use loadbalancer - for local use cluster